apiVersion: apps/v1
kind: Deployment
metadata:
  name: empire-dashboard
  namespace: nexia-empire
  labels:
    app: empire-dashboard
    version: v2.0.0
    component: nexia-supervisor
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: empire-dashboard
  template:
    metadata:
      labels:
        app: empire-dashboard
        version: v2.0.0
        component: nexia-supervisor
    spec:
      serviceAccountName: empire-dashboard-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: empire-dashboard
        image: registry.digitalocean.com/onlyoneapi/empire-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5002"
        - name: KUBECONFIG
          value: "/etc/kubeconfig/kubeconfig"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: empire-kubeconfig
      imagePullSecrets:
      - name: onlyoneapi-registry