apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-empire-config
  namespace: nexia-empire
data:
  build.sh: |
    #!/bin/bash
    set -e
    
    echo "🏗️ Building Empire Dashboard v2 with Kaniko"
    echo "📦 Registry: registry.digitalocean.com/onlyoneapi"
    echo "🏷️ Tag: empire-dashboard:$(git rev-parse --short HEAD)"
    
    # Execute Kaniko build
    /kaniko/executor \
      --context=git://github.com/ludovicpilet/empire-dashboard-v2.git \
      --dockerfile=Dockerfile \
      --destination=registry.digitalocean.com/onlyoneapi/empire-dashboard:latest \
      --destination=registry.digitalocean.com/onlyoneapi/empire-dashboard:$(git rev-parse --short HEAD) \
      --cache=true \
      --cache-ttl=24h
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-empire-build
  namespace: nexia-empire
  labels:
    app: kaniko-build
    component: empire-dashboard
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        command: ["/bin/sh"]
        args: ["/scripts/build.sh"]
        env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        volumeMounts:
        - name: build-script
          mountPath: /scripts
        - name: docker-config
          mountPath: /kaniko/.docker
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: build-script
        configMap:
          name: kaniko-empire-config
          defaultMode: 0755
      - name: docker-config
        secret:
          secretName: onlyoneapi-registry
          items:
          - key: .dockerconfigjson
            path: config.json