apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-empire-config
  namespace: nexia
data:
  build.sh: |
    #!/bin/bash
    set -e
    
    echo "🏗️ Building Empire Dashboard v2 with Kaniko"
    echo "📦 Registry: registry.digitalocean.com/onlyoneapi"
    echo "🏷️ Tag: empire-dashboard:$(git rev-parse --short HEAD)"
    
    # Execute Kaniko build
    /kaniko/executor \
      --context=git://github.com/ludovicpilet/empire-dashboard-v2.git \
      --dockerfile=Dockerfile \
      --destination=registry.digitalocean.com/onlyoneapi/blueocean-dashboard:latest \
      --destination=registry.digitalocean.com/onlyoneapi/blueocean-dashboard:$(git rev-parse --short HEAD) \
      --cache=true \
      --cache-ttl=24h
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-empire-build
  namespace: nexia
  labels:
    app: kaniko-build
    component: empire-dashboard
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --context=git://github.com/Digiclevr/empire-dashboard-v2.git
        - --dockerfile=Dockerfile
        - --destination=registry.digitalocean.com/onlyoneapi/blueocean-dashboard:latest
        - --cache=true
        - --cache-ttl=24h
        env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: docker-config
        secret:
          secretName: registry-blueocean
          items:
          - key: .dockerconfigjson
            path: config.json