apiVersion: v1
kind: ServiceAccount
metadata:
  name: blueocean-dashboard-sa
  namespace: nexia
  labels:
    app: blueocean-dashboard
    component: nexia-supervisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blueocean-dashboard-reader
  labels:
    app: blueocean-dashboard
    component: nexia-supervisor
rules:
- apiGroups: [""]
  resources: 
  - nodes
  - pods
  - services
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blueocean-dashboard-binding
  labels:
    app: blueocean-dashboard
    component: nexia-supervisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blueocean-dashboard-reader
subjects:
- kind: ServiceAccount
  name: blueocean-dashboard-sa
  namespace: nexia